"""Export a caption track to the formats downstream actually consumes.

Four targets, each with a different fidelity ceiling:

  JSON  the native render spec. Carries every keyframe; this is what the
        ClipForge renderer consumes and what the render cache hashes.
  ASS   Advanced SubStation Alpha. ffmpeg burns this directly
        (`-vf ass=file.ass`), and `\\kf` gives genuine word-by-word karaoke
        fill. Scale and offset animation is *not* expressible per-word in ASS
        without emitting one positioned Dialogue per word, which needs exact
        font metrics the engine only approximates — so ASS carries timing,
        colour and styling, and the JSON carries motion.
  VTT   WebVTT with inline timestamp tags, which gives word-level highlighting
        in browsers and on platforms that accept sidecar captions.
  SRT   Lowest common denominator: cue-level text, no word timing. Every
        platform accepts it.
"""

from __future__ import annotations

from .languages import apply_typography, rules_for
from .styles import CaptionStyle
from .types import CaptionTrack


def _ass_color(hex_color: str, alpha: str = "00") -> str:
    """`#RRGGBB` → `&HAABBGGRR`.

    ASS stores colour byte-reversed and its alpha is inverted: `00` is fully
    opaque, `FF` fully transparent. Both are easy to get backwards, and the
    result looks like a rendering bug rather than a colour bug.
    """
    value = hex_color.lstrip("#")
    if len(value) == 8:  # #RRGGBBAA
        rr, gg, bb, aa = value[0:2], value[2:4], value[4:6], value[6:8]
        alpha = f"{255 - int(aa, 16):02X}"
    else:
        rr, gg, bb = value[0:2], value[2:4], value[4:6]
    return f"&H{alpha}{bb}{gg}{rr}".upper()


def _ass_time(ms: int) -> str:
    """ASS uses centisecond precision: `H:MM:SS.cc`."""
    ms = max(0, ms)
    hours, rest = divmod(ms, 3_600_000)
    minutes, rest = divmod(rest, 60_000)
    seconds, millis = divmod(rest, 1000)
    return f"{hours:d}:{minutes:02d}:{seconds:02d}.{millis // 10:02d}"


def _srt_time(ms: int) -> str:
    ms = max(0, ms)
    hours, rest = divmod(ms, 3_600_000)
    minutes, rest = divmod(rest, 60_000)
    seconds, millis = divmod(rest, 1000)
    return f"{hours:02d}:{minutes:02d}:{seconds:02d},{millis:03d}"


def _vtt_time(ms: int) -> str:
    return _srt_time(ms).replace(",", ".")


def to_ass(track: CaptionTrack, style: CaptionStyle) -> str:
    """Render the track as an ASS subtitle file with karaoke timing."""
    rules = rules_for(track.language)

    # Alignment 2 = bottom centre. Margins position the text block inside the
    # caption box the layout planner produced, so ASS output lands in the same
    # place as the native renderer's.
    margin_l = track.box.x
    margin_r = max(0, 1080 - (track.box.x + track.box.width))
    margin_v = max(0, 1920 - (track.box.y + track.box.height))

    header = f"""[Script Info]
; Generated by ClipForge AI — caption engine
ScriptType: v4.00+
PlayResX: 1080
PlayResY: 1920
WrapStyle: 2
ScaledBorderAndShadow: yes
YCbCr Matrix: TV.709

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Default,{style.font_family},{style.font_size_px},{_ass_color(style.active_color)},{_ass_color(style.color)},{_ass_color(style.stroke_color)},{_ass_color(style.shadow_color or '#000000', 'A0')},{-1 if style.font_weight >= 700 else 0},0,0,0,100,100,0,0,1,{style.stroke_width_px // 2},{style.shadow_offset_px // 2},2,{margin_l},{margin_r},{margin_v},1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
"""

    lines: list[str] = [header]
    for cue in track.cues:
        parts: list[str] = []
        for line_index, line in enumerate(cue.lines):
            if line_index:
                parts.append("\\N")
            for word in line.words:
                if word.is_emoji:
                    # Emoji are not karaoke syllables; hold them for the rest
                    # of the cue so they do not flicker with the fill.
                    parts.append(word.text + " ")
                    continue
                centis = max(1, round(word.duration_ms / 10))
                text = apply_typography(word.text, rules)
                # \kf sweeps the fill across the word rather than switching it
                # instantly, which is what makes karaoke read as smooth.
                parts.append(f"{{\\kf{centis}}}{text} ")

        body = "".join(parts).rstrip()

        override = ""
        if cue.font_scale != 1.0:
            pct = round(cue.font_scale * 100)
            override = f"{{\\fscx{pct}\\fscy{pct}}}"

        speaker_color = track.speaker_colors.get(cue.speaker)
        if speaker_color:
            # Recolour the karaoke fill per speaker. Primary is the sung
            # colour in ASS, so this tints the active word only.
            override += f"{{\\1c{_ass_color(speaker_color)}}}"

        lines.append(
            f"Dialogue: 0,{_ass_time(cue.start_ms)},{_ass_time(cue.end_ms)},"
            f"Default,{cue.speaker},0,0,0,,{override}{body}"
        )

    return "\n".join(lines) + "\n"


def to_vtt(track: CaptionTrack, word_timing: bool = True) -> str:
    """WebVTT, optionally with inline per-word timestamp tags."""
    rules = rules_for(track.language)
    out: list[str] = ["WEBVTT", ""]

    for cue in track.cues:
        out.append(f"{cue.index}")
        out.append(f"{_vtt_time(cue.start_ms)} --> {_vtt_time(cue.end_ms)}")

        for line in cue.lines:
            if not word_timing:
                out.append(apply_typography(line.text, rules))
                continue
            parts: list[str] = []
            for word in line.words:
                text = apply_typography(word.text, rules)
                parts.append(f"<{_vtt_time(word.start_ms)}>{text}")
            out.append(" ".join(parts))

        out.append("")

    return "\n".join(out)


def to_srt(track: CaptionTrack) -> str:
    """SRT — cue-level only. Word timing does not survive this format."""
    rules = rules_for(track.language)
    out: list[str] = []
    for cue in track.cues:
        out.append(str(cue.index))
        out.append(f"{_srt_time(cue.start_ms)} --> {_srt_time(cue.end_ms)}")
        for line in cue.lines:
            out.append(apply_typography(line.text, rules))
        out.append("")
    return "\n".join(out)


def to_json(track: CaptionTrack, style: CaptionStyle) -> dict:
    """The native render spec — the only export that carries animation."""
    payload = track.to_dict()
    payload["style_spec"] = style.to_dict()
    return payload
